sonar.projectKey=cocinacompartida
sonar.projectName=Cocina Compartida
sonar.projectVersion=1.0

sonar.sources=cocina-compartida/src,cocina-compartida-api/src
sonar.tests=cocina-compartida/src,cocina-compartida-api/src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=cocina-compartida/coverage/cocina-compartida/lcov.info,cocina-compartida-api/coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.entity.ts
sonar.coverage.exclusions=**/*.spec.ts,**/*.entity.ts,**/*.module.ts,**/main.ts,**/*.css,**/*.html,**/*.interface.ts
