# Backend API (NestJS)
sonar.projectKey=CocinaCompartida-Backend
sonar.projectName=CocinaCompartida Backend API
sonar.projectVersion=1.0

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.token="Toquen"

# Source code
sonar.sources=cocina-compartida-api/src
sonar.tests=cocina-compartida-api/src
sonar.test.inclusions=**/*.spec.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.entity.ts
sonar.coverage.exclusions=**/*.spec.ts,**/*.entity.ts