sonar.projectKey=cocinacompartida
sonar.projectName=cocinacompartida
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000
sonar.login=sqp_dca4b8136fa76d9ac31bf8e0229cf09e845b034f