sonar.projectKey=CocinaCompartida-Backend
sonar.projectName=cocinacompartida-back-solution
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_e0a13b73c31ce0fe2c5d4e5ae53d2b5624723912

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/test-unitarios/**/*.spec.ts,**/test/**/*.spec.ts
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Files that are not production logic for Sonar analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.entity.ts,**/*.module.ts,src/main.ts

# Files excluded only from coverage expectation
sonar.coverage.exclusions=**/*.spec.ts,**/*.entity.ts,**/*.module.ts,src/main.ts
