sonar.projectKey=CocinaCompartida-Backend
sonar.projectName=CocinaCompartida Backend API1
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_64f24fb977e4fd6e80500fa12de52e7d50891510

# Source and tests configuration (Relative to current folder)
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/test-unitarios/**/*.spec.ts

# LCOV Report Path (Now matches the ./coverage from your updated package.json)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Files to EXCLUDE from SonarQube's logic (fixes 2.2k lines bug and fake code issues)
# We exclude node_modules, dist (compiled code), spec files as source, entities, modules and main.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.entity.ts,**/*.module.ts,src/main.ts

# Files to EXCLUDE strictly from coverage expectation (so they don't lower your %)
sonar.coverage.exclusions=**/*.spec.ts,**/*.entity.ts,**/*.module.ts,src/main.ts
