sonar.projectKey=cocinacompartida_front
sonar.projectName=cocinacompartida_front
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=squ_e0a13b73c31ce0fe2c5d4e5ae53d2b5624723912

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8

# Angular/Karma writes this file when running npm run test:cov
sonar.javascript.lcov.reportPaths=coverage/cocina-compartida/lcov.info

# Files that are not TypeScript production logic for Sonar analysis
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.spec.ts,src/assets/**,src/environments/**,src/main.ts,src/polyfills.ts,**/*.css,**/*.html

# Files excluded only from coverage expectation because they have no executable business logic
sonar.coverage.exclusions=**/*.spec.ts,src/environments/**,src/main.ts,src/polyfills.ts,src/app/app.config.ts,src/app/app.routes.ts,**/*.module.ts,**/*.interface.ts,**/*.css,**/*.html
