sonar.projectKey=cocinacompartida_front
sonar.projectName=cocinacompartida_front
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=sqp_dca4b8136fa76d9ac31bf8e0229cf09e845b034f

# Source and tests configuration
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Rutas del LCOV pattern en Angular (Angular genera coverage en esta carpeta)
# Nota mental: Sonar probará ambas rutas por formato
sonar.javascript.lcov.reportPaths=coverage/cocina-compartida/lcov.info,coverage/lcov.info

# Archivos ignorados como "código fuente" para las líneas de código (archivos spec, main.ts, environments)
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,src/assets/**,src/environments/**,src/main.ts,src/polyfills.ts

# Archivos omitidos de la evaluación de Testing (Para que no bajen tu porcentaje módulos sin lógica o interfaces)
sonar.coverage.exclusions=**/*.spec.ts,src/environments/**,src/main.ts,src/polyfills.ts,**/*.module.ts,**/*.interface.ts,**/*.css,**/*.html
